#!/usr/bin/env python3
"""Prevent delayed scheduled runs from publishing out of logical order."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import pathlib
import urllib.parse
import urllib.request
from collections.abc import Callable, Mapping
from typing import Any


def read_json(path: pathlib.Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"JSON object required: {path}")
    return value


def load_json_url(url: str) -> dict[str, Any]:
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "application/json",
            "Cache-Control": "no-cache",
            "User-Agent": "xuangu-deployment-order-guard/1.0",
        },
    )
    with urllib.request.urlopen(request, timeout=15) as response:
        value = json.loads(response.read().decode("utf-8"))
    if not isinstance(value, dict):
        raise ValueError("production latest snapshot must be a JSON object")
    return value


def aware_moment(value: Any, field: str) -> dt.datetime:
    try:
        parsed = dt.datetime.fromisoformat(str(value or "").replace("Z", "+00:00"))
    except (TypeError, ValueError) as exc:
        raise ValueError(f"timezone-aware {field} required") from exc
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise ValueError(f"timezone-aware {field} required")
    return parsed


def _automation(snapshot: Mapping[str, Any]) -> Mapping[str, Any]:
    value = snapshot.get("automation")
    return value if isinstance(value, Mapping) else {}


def scheduled_invocation(snapshot: Mapping[str, Any], *, required: bool) -> dt.datetime | None:
    automation = _automation(snapshot)
    if str(automation.get("trigger") or "") != "schedule":
        return None
    # Incoming snapshots generated by the current workflow must carry the
    # actual cron invocation.  Only already-published legacy snapshots may
    # fall back to their primary checkpoint for migration compatibility.
    value = automation.get("scheduled_invocation_slot")
    if value in (None, "") and not required:
        value = automation.get("scheduled_slot")
    if value in (None, ""):
        if required:
            raise ValueError("scheduled snapshot is missing its logical invocation slot")
        return None
    return aware_moment(value, "automation.scheduled_invocation_slot")


def publication_decision(
    incoming: Mapping[str, Any],
    production: Mapping[str, Any],
) -> dict[str, Any]:
    incoming_slot = scheduled_invocation(incoming, required=True)
    if incoming_slot is None:
        return {"should_publish": True, "reason": "non_scheduled_incoming"}

    production_slot = scheduled_invocation(production, required=False)
    if production_slot is not None and production_slot > incoming_slot:
        return {
            "should_publish": False,
            "reason": "production_logical_slot_is_newer",
            "incoming_slot": incoming_slot.isoformat(timespec="minutes"),
            "production_slot": production_slot.isoformat(timespec="minutes"),
            "production_snapshot_key": production.get("snapshot_key"),
        }
    if production_slot is not None and production_slot == incoming_slot:
        incoming_generated = aware_moment(incoming.get("generated_at"), "incoming generated_at")
        production_generated = aware_moment(
            production.get("generated_at"),
            "production generated_at",
        )
        if production_generated > incoming_generated:
            return {
                "should_publish": False,
                "reason": "production_same_slot_generation_is_newer",
                "incoming_slot": incoming_slot.isoformat(timespec="minutes"),
                "production_slot": production_slot.isoformat(timespec="minutes"),
                "production_snapshot_key": production.get("snapshot_key"),
            }
        if production_generated == incoming_generated:
            same_snapshot = production.get("snapshot_key") == incoming.get("snapshot_key")
            return {
                "should_publish": False,
                "reason": (
                    "same_snapshot_already_published"
                    if same_snapshot
                    else "same_slot_same_moment_snapshot_conflict"
                ),
                "incoming_slot": incoming_slot.isoformat(timespec="minutes"),
                "production_slot": production_slot.isoformat(timespec="minutes"),
                "production_snapshot_key": production.get("snapshot_key"),
            }
    return {
        "should_publish": True,
        "reason": "logical_order_ok",
        "incoming_slot": incoming_slot.isoformat(timespec="minutes"),
        "production_slot": (
            production_slot.isoformat(timespec="minutes") if production_slot else None
        ),
        "production_snapshot_key": production.get("snapshot_key"),
    }


def production_latest_url(base_url: str) -> str:
    root = base_url.rstrip("/") + "/"
    return urllib.parse.urljoin(root, "data/picks/latest.json")


def evaluate_path(
    path: pathlib.Path,
    *,
    base_url: str,
    fetcher: Callable[[str], dict[str, Any]] = load_json_url,
) -> dict[str, Any]:
    incoming = read_json(path)
    production = fetcher(production_latest_url(base_url))
    return publication_decision(incoming, production)


def write_output(result: Mapping[str, Any]) -> None:
    values = {
        "should_publish": "true" if result.get("should_publish") is True else "false",
        "reason": str(result.get("reason") or "unknown"),
    }
    output_path = os.environ.get("GITHUB_OUTPUT")
    lines = [f"{key}={value}" for key, value in values.items()]
    print("\n".join(lines))
    print(json.dumps(dict(result), ensure_ascii=False, sort_keys=True))
    if output_path:
        with open(output_path, "a", encoding="utf-8") as output:
            output.write("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", nargs="?", type=pathlib.Path, default=pathlib.Path("data/picks/latest.json"))
    parser.add_argument("--base-url", default="https://xuangu.alixjd.com")
    args = parser.parse_args()
    write_output(evaluate_path(args.path, base_url=args.base_url))


if __name__ == "__main__":
    main()
